<div class="page_content">
    <div id="container-fluid">
        <div class="row">
            <div id="contents" class="col-lg-12">
                 <div style="clear: both;"></div><br>
                <div class="panel panel-default">
                                <div class="panel-body">
            
<div class="container" >
    <h2>Terms & Conditions</h2>
    <div class="faq">
    	<p>
    	This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        <br><br>
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms and Conditions for access or usage www.busticketagent.com
        <br><br>
        The domain name www.ezeebits.com (hereinafter referred to as the "Website" is owned by EzeeInfo Cloud solutions Pvt Ltd).
        <br><br>
        For the purpose of these Terms and Conditions, wherever the context so requires, the term:
    	</p><br>
        <ul>
            <li>Any complaints and queries contact <span class="bold">9500007529 / 044-42866353</span> or write us to <span class="bold">support@ezeeinfo.in</span></li>
            <li>The passengers are requested to co-operate with the bus operators to maintain punctuality.</li>
            <li>The Ticket booked is not transferable.</li>
            <li>Please carry a valid photo id while traveling.</li>
            <li>Bus Operator reserves rights to change the seat while boarding.</li>
            <li>The Company does not accept responsibility for any injury, damage or loss caused by any accident. Delay or irregularity or any other natural calamities.</li>
            <li>Passengers are allowed to carry personal luggage at their own risk. Additional luggage will be charged.</li>
            <li>Smoking & Consumption of liquor is prohibited on board.</li>
            <li>Passengers hereby consent to receive communications by SMS / Email or calls from bus operator with regards to the services provided by them.</li>
            <li>By booking a ticket or by registering at EzeeBits, the customer acknowledges that BusticketAgents will call or email or SMS or send alerts to provide or request information regarding the customers bookings.</li>
        </ul>
    </div>
    
    <h2>Cancellation Policy</h2>
    <div class="faq">
        <ul>
            <li>Between 0 - 3 hours before departure time 100% Deduction</li>
            <li>Between 3 - 6 hours before departure time 50% Deduction</li>
            <li>Between 6 - 12 hours before departure time 25% Deduction</li>
            <li>Before 12 days from departure time 10% Deduction</li>
        </ul>
    </div>
    
    <h2>Failure Transactions</h2>
    <div class="faq">
        <ul>
            <li>A transaction might fail for several reasons and the customer's account / card might be debited without generation of the the ticket. In such cases, the customer is requested to immediately call our customer care number to re-confirm the failed transaction, before proceeding with a fresh transaction/ booking.</li>
            <li>If money is debited for the failed transactions, the same will be refunded back to the customer, as per the refund policy</li>
        </ul>
    </div>
    
    <h2>Refund Policy</h2>
    <div class="faq">
        <ul>
            <li>EzeeBits processes all refund requests, automatically on cancellation of the tickets. Considering the refund amount has to move through a network of banks, it can take 7 days to 15 business working days for the refund amount to be credited to the customer's account / card.</li>
            <li>The amount refunded to the customer will be transferred to the mode of payment used by the customer while booking the ticket. This may include bank account / debit / credit / cash card / electronic wallets</li>
            <li>In case the refund amount is not credited to the customer's account within 15 business working days, the customer is requested to send an email to support@ezeeinfo.in, along with the ticket details. We will endeavor to facilitate and support the customer in the getting the refund amount credited to their account.</li>
            <li>Refunds will not be processed for passengers who do not report at the boarding point on time. These passengers are called No-show passengers</li>
            <li>Any transaction charges, or facilitation charges, or ticket delivery charges, collected shall not be refunded if the tickets are cancelled by the customer.</li>
            <li>In the event of cancellation of a bus / service trip by the bus operator, EzeeBits will assist the passenger by providing an alternative service, subject to availability. In case an alternative is not available, then EzeeBits shall be liable to the passenger only to the extent of refunding the amount paid by the customer for the price of the ticket.</li>
        </ul>
    </div>
</div>
                                    
                </div>
                </div>
                </div>
        </div>
    </div>
</div>
