<div class="print-border"></div>
<div class="print-border-left"></div>
<div class="print-border-right"></div>



<table class="each-table" border="2" cellpadding="10" width="101%">
    <thead>
        <tr>
            <td colspan="12">
                <img align="left" style="margin-left: 20px;margin-top:30px;"
                    src="{$base_url}/assets/img/seenutransports-logo.png" alt="logo" width="150px">
                <h1 align="center">Seenu Transports Pvt Ltd</h1>
                <h3 align="center"><b>Expense Report</b></h3>
            </td>
        </tr>
        <tr>
            <td align="center" nowrap><b>Accounting Date</b></td>
            <td align="center" nowrap><b>S.No.</b> </td>
            <td align="center" nowrap><b>Account Name </b></td>
            <td align="left" nowrap><b>Costing Name</b></td>
            <td align="left" nowrap><b>Remarks</b> </td>
            <td align="left" nowrap><b>Reference/ Bill No. </b> </td>
            <td align="left" nowrap><b>Payment Type</b></td>
            <td align="center" nowrap><b>Debit</b></td>
        </tr>
    </thead>
    <tbody>
        {assign var=tot_items value=0}
        {foreach item=row from=$result key=k}
            <tr id="tr-{$row->code}">
                <td align="center">{$row->transactionDate|strtotime|date_format:"%d-%b-%Y"}</td>
                <td align="center"> {$k+1} </td>
                <td align="center" nowrap>{$row->cashbookVendor->contactCategory->name|default:'-'}</td>
                <td align="center" nowrap>{$row->cashbookVendor->name|default:'-'}</td>
                <td align="center" nowrap>{(($row->remarks|default:'-')|substr:5)|trim:'|'}</td>
                <td align="center" nowrap>{($row->voucherNumber|default:'-')}</td>
                <td align="center" nowrap>{($row->transactionMode->name)|substr:0:5}</td>
                <td align="right">{$row->amount|inr_format}</td>
            </tr>
            {assign var=tot_items value=$tot_items + $row->amount}
        {/foreach}
    </tbody>
    <tfoot>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td colspan="2" align="right"><b>Total</b></td>
            <td>{$tot_items|inr_format}</td>
        </tr>
    </tfoot>
</table>
<br><br>
<div style="text-align:center; position:relative; left:70px">
    <table border="1">
        <thead>
            <td><b>ACCOUNT TYPE</b></td>
            <td><b>COUNT</b></td>
            <td> <b>AMOUNT</b></td>
        </thead>
        <tbody>
            {assign var=tot_value value=0}
            {foreach item=row from=$accountDetails key=k}
                <tr>
                    <td>{$k}</td>
                    <td align = "center">{$row['count']}</td>
                    <td align = "right">{$row['amount']}</td>
                </tr>
                {assign var=tot_value value=$tot_value + $row['amount']}
            {/foreach}
        </tbody>
        <tfoot>
            <tr>
                <td><b>Total</b></td>
                <td></td>
                <td align = "right"><b>{$tot_value}</b></td>
            </tr>
        </tfoot>
    </table>
</div>


<div class="print-footer" id="print-footer">
    <table>
        <tr>
            <td width="35%"><b>Printed On : {$smarty.now|date_format:$ns_datetime_format}</b></td>
            <td width="25%"><b>Generated By: {$usr_login_name}</b></td>
        </tr>
    </table>
</div>
<style>
    .bold {
        font-weight: bold;
    }

    table {
        border-collapse: collapse;
    }

    table thead th,
    table thead td {
        font-weight: 100;
        padding: 10px;
    }

    table.bordered th,
    table.bordered td {
        border: 1px solid #000;
        padding: 10px;
    }

    div.print-border {
        position: fixed;
        bottom: 100px;
        left: 0;
        width: 100%;
        height: 1px;
        /* Set the height of the border as needed */
        background-color: #000;
        /* Set the border color as needed */
    }

    div.print-border-left,
    div.print-border-right {
        position: fixed;
        top: 30px;
        height: 100%;
        width: 1px;
        /* Set the width of the borders as needed */
        background-color: #000;
        /* Set the border color as needed */
        z-index: 1;
        /* Move the borders behind the content */
    }

    div.print-border-left {
        left: 6px;
    }

    div.print-border-right {
        right: 100px;
    }


    .print-header {
        position: fixed;
        top: 0;
    }
</style>

<style type="text/css" media="print">
    @media print {
        body {
            font-family: sans-serif;
            -webkit-print-color-adjust: exact !important;
            color-adjust: exact !important;
        }

        @page {
            size: A4 landscape;
        }

        div.print-border {
            position: fixed;
            bottom: 20px;
            left: 6px;
            width: 100%;
            height: 1px;
            /* Set the height of the border as needed */
            background-color: #000000;
            /* Set the border color as needed */
        }

        div.print-border-left,
        div.print-border-right {
            position: fixed;
            top: 0px;
            height: 97.5%;
            width: 1px;
            /* Set the width of the borders as needed */
            background-color: #000;
            /* Set the border color as needed */
            z-index: -1;
            /* Move the borders behind the content */
        }

        div.print-border-left {
            left: 7px;
        }

        div.print-border-right {
            right: 0;
        }

        .page-break {
            page-break-before: always;
        }

        .print-table {
            width: 100.5%;
        }

        .print-header {
            position: fixed;
            top: 0;
            width: 100%;
        }

        .each-table {
            position: relative;

        }

        .first_page {
            position: relative;
            top: 152px;

        }

        .page-break {
            page-break-before: always;
        }

        .page-break-after {
            page-break-after: always;
        }

        .table-top {
            position: relative;
            top: 200px;
        }

        .print-footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #333;
        }

        .page-break {
            page-break-before: always;
        }
    }
</style>
