<style>
    .text-center { text-align: center; }
    .fs-7 { font-size: 7px; }
    .fs-9 { font-size: 9px; }
    .bold { font-weight: bold; }
    .border-x { border-top: 1px solid #000; border-bottom: 1px solid #000; }
    .border-l { border-left: 1px solid #000; }
    .border-r { border-right: 1px solid #000; }
</style>

<div>
    <h2 class="text-center">e-Way Bill</h2>
</div>

<div>
    {'<br/>'|str_repeat:6}
</div>

<table width="100%" cellpadding="5">
    <tbody>
        <tr>
            <td width="35%">E-Way Bill No:</td>
            <td width="65%"><b class="fs-9">{$details->ewayBillNo}</b></td>
        </tr>
        <tr>
            <td width="35%">E-Way Bill Date:</td>
            <td width="65%"><b>{$details->createdAt|date_format:'%d/%m/%Y %l:%M %p'}</b></td>
        </tr>
        <tr>
            <td width="35%">Generated By:</td>
            <td width="65%"><b>{$details->transportDetails->gstin} - {$namespace_name|upper}</b></td>
        </tr>
        <tr>
            <td width="35%">Valid From:</td>
            <td width="65%"><b>{$details->createdAt|date_format:'%d/%m/%Y %l:%M %p'} [{$details->distance}Kms]</b></td>
        </tr>
        <tr>
            <td width="35%">Valid Until:</td>
            <td width="65%"><b>{$details->expiryDate|date_format:'%d/%m/%Y'}</b></td>
        </tr>
    </tbody>
</table>

<hr>

<table width="100%" cellpadding="5">
    <tbody>
        <tr>
            <td width="35%"><b>Part - A</b></td>
            <td width="65%"></td>
        </tr>
        <tr>
            <td width="35%">GSTIN of Supplier</td>
            <td width="65%"><b>{$details->fromTaxPayerDetails->gstin}, {$details->fromTaxPayerDetails->tradeName}</b></td>
        </tr>
        <tr>
            <td width="35%">Place of Dispatch</td>
            <td width="65%"><b>{$details->fromTaxPayerDetails->place}-{$details->fromTaxPayerDetails->pincode}</b></td>
        </tr>
        <tr>
            <td width="35%">GSTIN of Recipient</td>
            <td width="65%"><b>{$details->toTaxPayerDetails->gstin},{$details->toTaxPayerDetails->tradeName}</b></td>
        </tr>
        <tr>
            <td width="35%">Place of Delivery</td>
            <td width="65%"><b>{$details->toTaxPayerDetails->place}-{$details->toTaxPayerDetails->pincode}</b></td>
        </tr>
        <tr>
            <td width="35%">Document No.</td>
            <td width="65%"><b>{$details->documentNo}</b></td>
        </tr>
        <tr>
            <td width="35%">Document Date</td>
            <td width="65%"><b>{$details->documentDate|date_format:'%d/%m/%Y'}</b></td>
        </tr>
        <tr>
            <td width="35%">Transaction Type:</td>
            <td width="65%"><b>{$ewaybill_transaction_type[$details->transactionType]} </b></td>
        </tr>
        <tr>
            <td width="35%">Value of Goods</td>
            <td width="65%"><b>’ {$details->totalInvoiceValue}</b></td>
        </tr>
        <tr>
            <td width="35%">HSN Code</td>
            <td width="65%"><b>{$details->items[0]->hsnCode}</b></td>
        </tr>
        <tr>
            <td width="35%">Reason for Transportation</td>
            <td width="65%"><b>{$ewaybill_supply_type[$details->supplyType]} - {$ewaybill_sub_supply_type[$details->supplySubType]}</b></td>
        </tr>
        <tr>
            <td width="35%">Transporter</td>
            <td width="65%"><b>{$details->transportDetails->gstin} & {$namespace_name|upper}</b></td>
        </tr>
    </tbody>
</table>

<hr>

<table width="100%" cellpadding="5">
    <thead>
        <tr>
            <td colspan="7"><b>Part - B</b></td>
        </tr>
        <tr>
            <th width="10%" class="bold fs-7 border-x border-l">Mode</th>
            <th class="bold fs-7 border-x">Vehicle / Trans<br/> Doc No & DI.</th>
            <th class="bold fs-7 border-x">From</th>
            <th width="20%" class="bold fs-7 border-x">Entered Date</th>
            <th width="20%" class="bold fs-7 border-x">Entered By</th>
            <th class="bold fs-7 border-x">CEWB No. <br/> (If any)</th>
            <th class="bold fs-7 border-x border-r">Multi Veh.Info <br/> (If any)</th>
        </tr>
    </thead>
    <tbody>
        {foreach item=row from=$details->vehicleDetails key=k}
            <tr>
                <td width="10%" class="fs-7 border-x border-l">{$ewaybill_transportation_mode[$row->transportDetails->transportMode]}</td>
                <td class="fs-7 border-x">{$row->vehicle->registationNumber}</td>
                <td class="fs-7 border-x">{$row->fromStation->name}</td>
                <td width="20%" class="fs-7 border-x">{$row->updatedAt|date_format:'%d/%m/%Y %l:%M %p'}</td>
                <td width="20%" class="fs-7 border-x">{$row->transportDetails->gstin}</td>
                <td class="fs-7 border-x">{$row->tripSheetNo}</td>
                <td class="fs-7 border-x border-r">-</td>
            </tr>
        {/foreach}
    </tbody>
</table>

<div>
    {'<br/>'|str_repeat:5}
</div>
<hr>