<div class="text-right">
    <div class="btn-group btn-group-sm">
        <a href="javascript:;" class="btn btn-primary" onclick="ewaybillUpdateVehicle()">Update Part-B</a>
    </div>
    <div class="btn-group btn-group-sm">
        <a href="cargo/ewaybill-summary?code={$details->ewayBillNo}" class="btn btn-default" target="_blank">Download</a>
    </div>
</div>

<div>
    <h5><b>e-Way Bill Details</b></h5>
</div>

<table width="100%" cellpadding="5">
    <tbody>
        <tr>
            <td width="20%"><b>E-Way Bill No:</b></td>
            <td width="30%">{$details->ewayBillNo}</td>
            <td width="20%"><b>E-Way Bill Date:</b></td>
            <td width="30%">{$details->createdAt|date_format:'%d/%m/%Y %l:%M %p'}</td>
        </tr>
        <tr>
            <td width="20%"><b>Valid From:</b></td>
            <td width="30%">{$details->createdAt|date_format:'%d/%m/%Y %l:%M %p'} [{$details->distance}Kms]</td>
            <td width="20%"><b>Valid Until:</b></td>
            <td width="30%">{$details->expiryDate|date_format:'%d/%m/%Y'}</td>
        </tr>
        <tr>
            <td width="20%"><b>Generated By:</b></td>
            <td width="30%">{$details->transportDetails->gstin} - {$namespace_name|upper}</td>
        </tr>
    </tbody>
</table>

<hr>

<h6><b>Part - A</b></h6>
<table width="100%" cellpadding="5">
    <tbody>
        <tr>
            <td width="20%"><b>GSTIN of Supplier</b></td>
            <td width="30%">{$details->fromTaxPayerDetails->gstin}, {$details->fromTaxPayerDetails->tradeName}</td>
            <td width="20%"><b>GSTIN of Recipient</b></td>
            <td width="30%">{$details->toTaxPayerDetails->gstin},{$details->toTaxPayerDetails->tradeName}</td>
        </tr>
        <tr>
            <td width="20%"><b>Place of Dispatch</b></td>
            <td width="30%">{$details->fromTaxPayerDetails->place}-{$details->fromTaxPayerDetails->pincode}</td>
            <td width="20%"><b>Place of Delivery</b></td>
            <td width="30%">{$details->toTaxPayerDetails->place}-{$details->toTaxPayerDetails->pincode}</td>
        </tr>
        <tr>
            <td width="20%"><b>Document No.</b></td>
            <td width="30%">{$details->documentNo}</td>
            <td width="20%"><b>Transaction Type:</b></td>
            <td width="30%">{$ewaybill_transaction_type[$details->transactionType]} </td>
        </tr>
        <tr>
            <td width="20%"><b>Document Date</b></td>
            <td width="30%">{$details->documentDate|date_format:'%d/%m/%Y'}</td>
            <td width="20%"><b>HSN Code</b></td>
            <td width="30%">{$details->items[0]->hsnCode}</td>
        </tr>
        <tr>
            <td width="20%"><b>Value of Goods</b></td>
            <td width="30%">{$details->totalInvoiceValue}</td>
            <td width="20%"><b>Reason for Transportation</b></td>
            <td width="30%">{$ewaybill_supply_type[$details->supplyType]} - {$ewaybill_sub_supply_type[$details->supplySubType]}</td>
        </tr>
        <tr>
            <td width="20%"><b>Transporter</b></td>
            <td width="30%">{$details->transportDetails->gstin} & {$namespace_name|upper}</td>
        </tr>
    </tbody>
</table>

<hr>

<h6><b>Part - B</b></h6>
<table class="table table-bordered" width="100%" cellpadding="5">
    <thead>
        <tr class="active">
            <th width="10%" class="bold fs-7 border-x border-l">Mode</th>
            <th class="bold fs-7 border-x">Vehicle / Trans<br/> Doc No & DI.</th>
            <th class="bold fs-7 border-x">From</th>
            <th width="20%" class="bold fs-7 border-x">Entered Date</th>
            <th width="20%" class="bold fs-7 border-x">Entered By</th>
            <th class="bold fs-7 border-x">CEWB No. <br/> (If any)</th>
            <th class="bold fs-7 border-x border-r">Multi Veh.Info <br/> (If any)</th>
        </tr>
    </thead>
    <tbody>
        {foreach item=row from=$details->vehicleDetails key=k}
            <tr>
                <td width="10%" class="fs-7 border-x border-l">{$ewaybill_transportation_mode[$row->transportDetails->transportMode]}</td>
                <td class="fs-7 border-x">{$row->vehicle->registationNumber}</td>
                <td class="fs-7 border-x">{$row->fromStation->name}</td>
                <td width="20%" class="fs-7 border-x">{$row->updatedAt|date_format:'%d/%m/%Y %l:%M %p'}</td>
                <td width="20%" class="fs-7 border-x">{$row->transportDetails->gstin}</td>
                <td class="fs-7 border-x">{$row->tripSheetNo}</td>
                <td class="fs-7 border-x border-r">-</td>
            </tr>
        {/foreach}
    </tbody>
</table>